NAME    = openmpi_$(ROLLCOMPILER)_$(ROLLNETWORK)
VERSION = 1.6.5
RELEASE = 0
RPM.EXTRAS         = AutoReq:No

RPM.EXTRAS = "AutoReq: no"

SRC_SUBDIR          = openmpi

OPENMPI_NAME        = openmpi
OPENMPI_VERSION     = $(VERSION)
OPENMPI_PKG_SUFFIX  = tar.gz
OPENMPI_SOURCE_PKG  = $(OPENMPI_NAME)-$(OPENMPI_VERSION).$(OPENMPI_PKG_SUFFIX)
OPENMPI_SOURCE_DIR  = $(OPENMPI_SOURCE_PKG:%.$(OPENMPI_PKG_SUFFIX)=%)

KNEM_NAME           = knem
KNEM_VERSION        = 1.1.0
KNEM_PKG_SUFFIX     = tar.gz
KNEM_SOURCE_PKG     = $(KNEM_NAME)-$(KNEM_VERSION).$(KNEM_PKG_SUFFIX)
KNEM_SOURCE_DIR     = $(KNEM_SOURCE_PKG:%.$(KNEM_PKG_SUFFIX)=%)

TAR_GZ_PKGS         = $(OPENMPI_SOURCE_PKG) $(KNEM_SOURCE_PKG)
