#!/bin/bash
COMPS='intel pgi gnu'
 
MPIS='openmpi mvapich2'

NETS='ib mx'

for COMP in ${COMPS}; do
  for NET in ${NETS}; do

# MPICH

    /bin/echo ${MPIS} | /bin/grep -s 'mpich\>'
    if test $? -eq 0; then

/bin/mkdir -m 0755 -p /opt/modulefiles/mpi/.${COMP}/mpich_${NET}

/bin/cat >  /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/1.2.7 <<END
#%Module1.0
module-whatis "mpich_${NET} mpi stack"
module-whatis "Version: 1.2.7"
set mpiHome /opt/mpich/${COMP}/${NET}
setenv MPIHOME \$mpiHome
prepend-path PATH \$mpiHome/bin
prepend-path LD_LIBRARY_PATH \$mpiHome/lib
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/1.2.7

/bin/cat > /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/.version.1.2.7 <<END
#%Module1.0
set ModulesVersion "1.2.7"
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/.version.1.2.7

/bin/ln -s /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/.version.1.2.7 \
           /opt/modulefiles/mpi/.${COMP}/mpich_${NET}/.version

    fi

# MPICH2

    /bin/echo ${MPIS} | /bin/grep -s mpich2
    if test $? -eq 0; then

/bin/mkdir -m 0755 -p /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}

/bin/cat > /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/1.0.7 <<END
#%Module1.0
module-whatis "mpich2_${NET} mpi stack"
module-whatis "Version: 1.0.7"
set mpiHome /opt/mpich2/${COMP}/${NET}
setenv MPIHOME \$mpiHome
prepend-path PATH \$mpiHome/bin
prepend-path LD_LIBRARY_PATH \$mpiHome/lib:\$mpiHome/lib/share
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/1.0.7

/bin/cat > /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/.version.1.0.7 <<END
#%Module1.0
set ModulesVersion "1.0.7"
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/.version.1.0.7

/bin/ln -s /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/.version.1.0.7 \
           /opt/modulefiles/mpi/.${COMP}/mpich2_${NET}/.version

    fi

# MVAPICH2

    /bin/echo ${MPIS} | /bin/grep -s mvapich2
    if test $? -eq 0; then

/bin/mkdir -m 0755 -p /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}

/bin/cat > /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/1.7 <<END
#%Module1.0
module-whatis "mvapich2_${NET} mpi stack"
module-whatis "Version: 1.7"
set mpiHome /opt/mvapich2/${COMP}/${NET}
setenv MPIHOME \$mpiHome
prepend-path PATH \$mpiHome/bin
prepend-path LD_LIBRARY_PATH \$mpiHome/lib:/opt/mvapich2/lib
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/1.7

/bin/cat > /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/.version.1.7 << END
#%Module1.0
set ModulesVersion "1.7"
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/.version.1.7

/bin/ln -s /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/.version.1.7 \
           /opt/modulefiles/mpi/.${COMP}/mvapich2_${NET}/.version

    fi

# OPENMPI

    /bin/echo ${MPIS} | /bin/grep -s openmpi
    if test $? -eq 0; then

/bin/mkdir -m 0755 -p /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}

/bin/cat > /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/1.4.1 << END
#%Module1.0
module-whatis "openmpi_${NET} mpi stack"
module-whatis "Version: 1.4.1"
set mpiHome /opt/openmpi/${COMP}/${NET}
setenv MPIHOME \$mpiHome
prepend-path PATH \$mpiHome/bin
prepend-path LD_LIBRARY_PATH \$mpiHome/lib
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/1.4.1

/bin/cat > /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/.version.1.4.1 << END
#%Module1.0
set ModulesVersion "1.4.1"
END
/bin/chmod 0644 /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/.version.1.4.1

/bin/ln -s /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/.version.1.4.1 \
           /opt/modulefiles/mpi/.${COMP}/openmpi_${NET}/.version

    fi

  done
done

