#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "mpich2_ROLLNETWORK mpi stack"
module-whatis "Version: VERSION"
set mpiHome /opt/mpich2/COMPILERNAME/ROLLNETWORK
setenv MPIHOME \$mpiHome
prepend-path PATH \$mpiHome/bin
prepend-path LD_LIBRARY_PATH \$mpiHome/lib

END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )

