ifndef ROLLNETWORK
  ROLLNETWORK = eth
endif
ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
else
  COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))
endif

NAME    = mpich2_$(COMPILERNAME)_$(ROLLNETWORK)
VERSION = 1.5
RELEASE = 1
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR        = mpich2

MPICH2_NAME        = mpich2
MPICH2_VERSION     = $(VERSION)
MPICH2_PKG_SUFFIX  = tar.gz
MPICH2_SOURCE_PKG  = $(MPICH2_NAME)-$(MPICH2_VERSION).$(MPICH2_PKG_SUFFIX)
MPICH2_SOURCE_DIR  = $(MPICH2_SOURCE_PKG:%.$(MPICH2_PKG_SUFFIX)=%)

TAR_GZ_PKGS          = $(MPICH2_SOURCE_PKG)
