NAME    = mpich2_$(ROLLCOMPILER)_$(ROLLNETWORK)
VERSION = 1.5
RELEASE = 5

SRC_SUBDIR        = mpich2

MPICH2_NAME        = mpich2
MPICH2_VERSION     = $(VERSION)
MPICH2_PKG_SUFFIX  = tar.gz
MPICH2_SOURCE_PKG  = $(MPICH2_NAME)-$(MPICH2_VERSION).$(MPICH2_PKG_SUFFIX)
MPICH2_SOURCE_DIR  = $(MPICH2_SOURCE_PKG:%.$(MPICH2_PKG_SUFFIX)=%)

TAR_GZ_PKGS          = $(MPICH2_SOURCE_PKG)
