NAME    = mvapich2_$(ROLLCOMPILER)_$(ROLLNETWORK)
VERSION = 1.9
RELEASE = 6

RPM.EXTRAS = "AutoReq: no"

SRC_SUBDIR           = mvapich2

MVAPICH2_NAME        = mvapich2
MVAPICH2_VERSION     = $(VERSION)
MVAPICH2_PKG_SUFFIX  = tgz
MVAPICH2_SOURCE_PKG  = $(MVAPICH2_NAME)-$(MVAPICH2_VERSION).$(MVAPICH2_PKG_SUFFIX)
MVAPICH2_SOURCE_DIR  = $(MVAPICH2_SOURCE_PKG:%.$(MVAPICH2_PKG_SUFFIX)=%)

LIMIC_NAME           = limic.ko

BARE_FILES           = $(LIMIC_NAME)
TGZ_PKGS             = $(MVAPICH2_SOURCE_PKG)
